"""End-to-end test of the full pipeline.

Runs on synthetic data generated by `tests/fixtures/make_synthetic_h5.py`, so it
executes without access to the real libraries and without network. The synthetic
populations are planted with a known composition shift between the two
timepoints, which gives the test something substantive to assert: the pipeline
must recover the shift, not merely finish without raising.

Marked `integration` because it takes ~90 s. Run with `make integration`.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
import yaml

from screye.config import Config
from screye.pipeline import run

REPO = Path(__file__).resolve().parents[1]

pytestmark = pytest.mark.integration


@pytest.fixture(scope="module")
def synthetic_config(tmp_path_factory) -> Config:
    """Generate synthetic CellRanger files and a config pointing at them."""
    workdir = tmp_path_factory.mktemp("synthetic")
    subprocess.run(
        [sys.executable, str(REPO / "tests/fixtures/make_synthetic_h5.py"),
         "--markers", str(REPO / "config/markers_compartment.yaml"),
         "--outdir", str(workdir / "data"),
         "--n-cells", "800"],
        check=True, capture_output=True,
    )

    base = yaml.safe_load((REPO / "config/config.yaml").read_text())
    base["samples"] = [
        {"name": "day5", "h5": str(workdir / "data/day5_filtered_feature_bc_matrix.h5"),
         "timepoint": "5dpf"},
        {"name": "day8", "h5": str(workdir / "data/day8_filtered_feature_bc_matrix.h5"),
         "timepoint": "8dpf"},
    ]
    base["outdir"] = str(workdir / "results")
    base["markers_file"] = str(REPO / "config/markers_ocular.yaml")
    base["compartment_markers"] = str(REPO / "config/markers_compartment.yaml")

    cfg_path = workdir / "config.yaml"
    cfg_path.write_text(yaml.safe_dump(base))
    return Config.from_yaml(cfg_path)


@pytest.fixture(scope="module")
def result(synthetic_config):
    return run(synthetic_config), synthetic_config


def test_pipeline_produces_every_declared_output(result):
    _, cfg = result
    expected = [
        "pass1_compartment_evidence.csv",
        "ocular/subcluster_celltype_scores.csv",
        "ocular/ocular.h5ad",
        "ocular/figures/pass2_ocular_umap.pdf",
        "ocular/figures/pass2_ocular_umap.svg",
        "ocular/figures/pass2_ocular_cell_types.png",
        "ocular/figures/pass2_ocular_composition.png",
        "neural/neural.h5ad",
        "figures/pass1_compartment_scores.pdf",
        "figures/pass1_compartment_umap.png",
        "figures/pass1_compartment_fine_umap.png",
        "cluster_celltype_scores.csv",
        "cluster_markers_wilcoxon.csv",
        "celltype_counts.csv",
        "processed.h5ad",
        "run_manifest.json",
        "figures/umap_overview.png",
        "figures/umap_cell_types.png",
        "figures/tsne_overview.png",
        "figures/tsne_cell_types.png",
        "figures/cluster_composition_by_sample.png",
        "figures/qc_violin_by_sample.png",
    ]
    missing = [f for f in expected if not (cfg.outdir / f).exists()]
    assert not missing, f"pipeline did not write: {missing}"


def test_embeddings_and_labels_are_attached(result):
    adata, _ = result
    assert "X_umap" in adata.obsm
    assert "X_tsne" in adata.obsm
    assert adata.obs["cell_type"].notna().all()
    assert adata.obs["leiden"].nunique() > 1


def test_both_samples_survive_qc(result):
    """A filter that silently removes an entire library is the failure that
    matters most, and the one least likely to raise."""
    adata, _ = result
    counts = adata.obs["sample"].value_counts()
    assert set(counts.index) == {"day5", "day8"}
    assert counts.min() > 100


def test_planted_composition_shift_is_recovered(result):
    """Synthetic day8 has more rods and fewer proliferating cells by design."""
    adata, _ = result
    frac = (
        adata.obs.groupby("sample", observed=True)["cell_type"]
        .value_counts(normalize=True).unstack(fill_value=0.0)
    )
    if "rod_photoreceptor" in frac.columns:
        assert frac.loc["day8", "rod_photoreceptor"] > frac.loc["day5", "rod_photoreceptor"]
    if "proliferating" in frac.columns:
        assert frac.loc["day5", "proliferating"] > frac.loc["day8", "proliferating"]


def test_manifest_records_input_checksums(result):
    """Provenance must tie outputs to the exact inputs that produced them."""
    import json

    _, cfg = result
    manifest = json.loads((cfg.outdir / "run_manifest.json").read_text())
    assert len(manifest["inputs"]) == 2
    assert all(len(i["sha256"]) == 64 for i in manifest["inputs"])
    assert manifest["packages"]["scanpy"] != "not installed"
    assert manifest["seed"] == cfg.seed
